(() => {
  'use strict';
  const cfg=window.IJR_OOP_LOGIC_CONFIG,$=id=>document.getElementById(id);
  const sb=window.supabase.createClient(cfg.supabaseUrl,cfg.supabasePublishableKey,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});
  const state={attemptId:null,token:null,snapshot:null,current:null,selected:'',startedAt:null,timer:null,pendingSnapshot:null};

  const GUIDES={
    class_object:{title:'Class and object · Clase y objeto',copy:'<p>Una <strong>clase</strong> define una estructura reutilizable. Un <strong>objeto</strong> es una instancia concreta creada a partir de esa definición.</p>',steps:['Identifica si el enunciado habla de la definición o de una instancia concreta.','Separa “qué puede tener/hacer” de “qué objeto existe ahora”.','Elige la opción que respete esa diferencia.'],hints:['Piensa en plantilla frente a ejemplar concreto.','Busca la palabra clase, objeto, instancia o constructor.','La clase define; el objeto existe como instancia.']},
    state_behavior:{title:'State and behavior · Estado y comportamiento',copy:'<p>El <strong>estado</strong> son los datos que describen un objeto. El <strong>comportamiento</strong> son las acciones que puede ejecutar mediante métodos.</p>',steps:['Subraya sustantivos/datos: suelen ser estado.','Subraya verbos/acciones: suelen ser métodos.','Comprueba qué miembro cambia o consulta el estado.'],hints:['Dato = estado; acción = comportamiento.','Busca el miembro que parece un verbo o una llamada con paréntesis.','Un método representa comportamiento.']},
    constructor:{title:'Constructor and valid state · Constructor',copy:'<p>El constructor establece el <strong>estado inicial</strong> necesario para que un objeto nazca listo para usarse.</p>',steps:['Imagina el momento exacto en que nace el objeto.','Pregunta qué datos deben existir desde el inicio.','Descarta opciones que confunden constructor con ejecutar toda la aplicación.'],hints:['Se ejecuta al crear la instancia.','Debe dejar el objeto en un estado inicial coherente.','Su función principal es inicializar el objeto.']},
    encapsulation:{title:'Encapsulation · Encapsulamiento',copy:'<p>Encapsular significa controlar el acceso y la modificación del estado para mantener <strong>reglas e invariantes</strong> del objeto.</p>',steps:['Identifica qué dato interno se quiere proteger.','Pregunta qué cambios deberían ser válidos o inválidos.','Prefiere el diseño que centraliza esas reglas en métodos/propiedades.'],hints:['No se trata de esconder por esconder.','El objetivo es controlar modificaciones válidas.','Protege invariantes del estado.']},
    self_this:{title:'self / this · Objeto actual',copy:'<p><code>self</code> en Python y <code>this</code> en Java permiten referirse al <strong>objeto concreto</strong> que está ejecutando un método de instancia.</p>',steps:['Imagina dos objetos distintos de la misma clase.','Ejecuta mentalmente el mismo método en cada uno.','Decide a cuál estado apunta self/this en cada llamada.'],hints:['No representa todas las instancias a la vez.','Apunta al receptor de la llamada.','Es el objeto actual.']},
    references_state:{title:'References and shared state · Referencias',copy:'<p>Dos variables pueden apuntar al <strong>mismo objeto</strong>. Si una referencia modifica ese objeto, la otra observa el nuevo estado.</p>',steps:['Dibuja el objeto una sola vez.','Dibuja flechas desde cada referencia al mismo objeto.','Aplica la mutación sobre ese único estado y vuelve a leerlo.'],hints:['Cuenta objetos, no nombres de variables.','Dos referencias no implican dos instancias.','Actualiza el mismo objeto una sola vez por cada llamada.']},
    inheritance:{title:'Inheritance · Herencia',copy:'<p>La herencia modela una relación <strong>is-a / es-un</strong>: una subclase es una especialización de una superclase.</p>',steps:['Lee la relación en voz alta: “Child es un Base”.','Pregunta si esa frase tiene sentido semántico.','No confundas is-a con has-a.'],hints:['Herencia expresa especialización.','Subclase → es-un tipo de → superclase.','La palabra clave es is-a.']},
    polymorphism:{title:'Polymorphism · Polimorfismo',copy:'<p>Con overriding, una referencia general puede apuntar a objetos específicos y la llamada a un método se resuelve usando la <strong>implementación del objeto real</strong>.</p>',steps:['Distingue el tipo declarado de la referencia.','Identifica la clase real del objeto creado.','Busca si el método fue sobrescrito y decide qué implementación responde.'],hints:['Tipo de referencia y clase real pueden diferir.','Busca overriding / @Override.','La implementación del objeto real responde a la llamada.']},
    composition:{title:'Composition · Composición',copy:'<p>La composición modela una relación <strong>has-a / tiene-un</strong>: un objeto contiene o utiliza otro objeto para colaborar.</p>',steps:['Busca un objeto guardado como campo/atributo de otro.','Lee la relación como “A tiene un B”.','Descarta herencia si A no es un tipo de B.'],hints:['Pregunta “¿tiene-un?” en lugar de “¿es-un?”.','Un objeto colabora con otro.','Eso describe composición.']},
    abstraction:{title:'Abstraction · Abstracción',copy:'<p>Una abstracción o interfaz define un <strong>contrato</strong>: qué capacidad se espera sin exigir que todas las implementaciones compartan exactamente el mismo detalle interno.</p>',steps:['Identifica la capacidad común que se exige.','Separa el “qué debe hacer” del “cómo lo hace”.','Elige la opción que permita implementaciones distintas bajo un contrato común.'],hints:['Piensa en contrato.','Define el qué, no todos los detalles del cómo.','Eso permite varias implementaciones.']},
    integrated_trace:{title:'Integrated object trace · Reto integrado',copy:'<p>Para rastrear objetos combina constructor, estado, referencias y llamadas. El truco es contar <strong>instancias reales</strong> y actualizar su estado en orden.</p>',steps:['Dibuja cada instancia creada por el constructor.','Conecta las referencias al objeto correcto.','Ejecuta cada método en orden y actualiza el estado después de cada llamada.'],hints:['No crees un objeto nuevo si solo hay una asignación de referencia.','Actualiza el estado en el orden exacto de las llamadas.','Lee el valor final después de todas las mutaciones.']}
  };

  async function rpc(name,args={}){const {data,error}=await sb.rpc(name,args);if(error)throw new Error(error.message||'Backend error');return data}
  function esc(v=''){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
  function fmtGrade(v){return Number(v??1).toFixed(2)}
  function currentCheckpoint(s=state.snapshot){return Array.from(s?.checkpoints||[]).find(x=>!x.completed)||null}
  function save(){if(state.attemptId&&state.token)sessionStorage.setItem(cfg.sessionKey,JSON.stringify({attemptId:state.attemptId,token:state.token}))}
  function clearSaved(){sessionStorage.removeItem(cfg.sessionKey)}
  function setStatus(msg,kind=''){const e=$('activityStatus');e.textContent=msg;e.className=kind?kind:''}
  function setupStatus(msg,bad=false){$('setupStatus').textContent=msg||'';$('setupStatus').style.color=bad?'#b42318':''}
  function normalizeSnippet(v){return String(v||'').replace(/\\\\n/g,'\n')}
  function fmtElapsed(ms){const s=Math.max(0,Math.floor(ms/1000)),m=Math.floor(s/60),r=s%60;return `${String(m).padStart(2,'0')}:${String(r).padStart(2,'0')}`}
  function elapsed(){return state.startedAt?Date.now()-state.startedAt.getTime():0}
  function startTimer(v){const d=v?new Date(v):new Date();state.startedAt=Number.isNaN(d.getTime())?new Date():d;clearInterval(state.timer);const tick=()=>{$('timeLabel').textContent=`${fmtElapsed(elapsed())} / ${String(cfg.targetMinutes).padStart(2,'0')}:00`};tick();state.timer=setInterval(tick,1000)}
  function setNetwork(){const online=navigator.onLine!==false,b=$('networkBadge');b.textContent=online?'Online':'Offline';b.classList.toggle('attention',!online)}
  window.addEventListener('online',setNetwork);window.addEventListener('offline',setNetwork);setNetwork();

  function syncTeamUI(){const size=Number($('teamSize').value||2);$('student2Wrap').classList.toggle('hidden-member',size<2);$('student3Wrap').classList.toggle('hidden-member',size<3);$('student2').required=size>=2;$('student3').required=size>=3;if(size<2)$('student2').value='';if(size<3)$('student3').value=''}
  $('teamSize').addEventListener('change',syncTeamUI);syncTeamUI();
  function readNames(){const size=Number($('teamSize').value||2),arr=[$('student1').value.trim()];if(size>=2)arr.push($('student2').value.trim());if(size>=3)arr.push($('student3').value.trim());return arr}

  function updateMetrics(s){state.snapshot=s;const cps=Array.from(s?.checkpoints||[]),done=Number(s?.completed_count??cps.filter(x=>x.completed).length),total=Number(s?.checkpoint_count||cfg.questionCount);$('progressText').textContent=`${done} / ${total}`;$('progressBar').style.width=`${Math.min(100,done/Math.max(1,total)*100)}%`;$('gradeLabel').textContent=`Proyección ${fmtGrade(s?.projected_grade??s?.grade)}`;const rem=Number(s?.help_tokens_remaining??cfg.helpTokenLimit);$('helpBadge').textContent=`${rem} ayuda${rem===1?'':'s'}`;$('helpRemaining').textContent=`${rem} de ${cfg.helpTokenLimit}`;$('helpButton').disabled=rem<=0;$('teamLabel').textContent=`${s?.group_code||''} · ${s?.student_label||'Equipo'}`;$('packLabel').textContent=`Pack ${String(s?.variant_pack??'?').padStart(2,'0')}`;$('finishHelps').textContent=`${Number(s?.help_tokens_used||0)} / ${cfg.helpTokenLimit}`;}
  function renderRail(cps,key){$('questionRail').innerHTML=cps.map(cp=>`<span class="question-dot ${cp.completed?'done':cp.key===key?'active':''}"></span>`).join('')}

  function renderQuestion(cp){state.current=cp;state.selected='';const guide=GUIDES[cp.topic]||GUIDES.integrated_trace;$('topicTag').textContent=String(cp.topic||'oop').replaceAll('_',' ').toUpperCase();$('conceptTitle').textContent=guide.title;$('conceptCopy').innerHTML=guide.copy;$('thinkingSteps').innerHTML=guide.steps.map(x=>`<li>${x}</li>`).join('');$('questionPrompt').textContent=cp.prompt||cp.title;const snippet=normalizeSnippet(cp.code);$('codeSnippet').classList.toggle('hidden',!snippet);$('codeSnippet').textContent=snippet;$('helpPanel').classList.add('hidden');$('revealButton').disabled=false;$('skipButton').disabled=false;$('validateButton').disabled=true;const choices=Array.isArray(cp.choices)?cp.choices:[];$('choiceOptions').innerHTML=choices.map((choice,i)=>`<button type="button" class="choice-option" data-value="${encodeURIComponent(String(choice))}"><span>${String.fromCharCode(65+i)}</span><strong>${esc(choice)}</strong></button>`).join('');$('choiceOptions').querySelectorAll('.choice-option').forEach(btn=>btn.addEventListener('click',()=>{$('choiceOptions').querySelectorAll('.choice-option').forEach(x=>x.classList.remove('selected'));btn.classList.add('selected');state.selected=decodeURIComponent(btn.dataset.value);$('validateButton').disabled=false;setStatus('Respuesta seleccionada. Valida cuando el equipo pueda justificarla.');}));setStatus('Lee, discute y selecciona una respuesta.');$('penaltyStatus').textContent='Solo una respuesta incorrecta validada reduce la proyección.';}

  function render(s){updateMetrics(s);$('setupPanel').classList.add('hidden');const cps=Array.from(s?.checkpoints||[]),done=Number(s?.completed_count||0),total=Number(s?.checkpoint_count||cfg.questionCount);startTimer(s?.started_at);if(s?.completed){clearInterval(state.timer);$('workspacePanel').classList.add('hidden');$('finishPanel').classList.remove('hidden');$('finishQuestions').textContent=`${done} / ${total}`;$('finishGrade').textContent=fmtGrade(s?.grade);$('finishTime').textContent=fmtElapsed(elapsed());clearSaved();return;}const cp=currentCheckpoint(s);if(!cp){setStatus('No se encontró la siguiente pregunta. Recarga la sesión.','bad');return;}$('questionLabel').textContent=`Pregunta ${Number(cp.sequence||done+1)} de ${total}`;renderRail(cps,cp.key);renderQuestion(cp);$('finishPanel').classList.add('hidden');$('workspacePanel').classList.remove('hidden');}

  $('registrationForm').addEventListener('submit',async e=>{e.preventDefault();const group=$('groupCode').value,names=readNames();if(!group||names.some(n=>n.length<2)||new Set(names.map(n=>n.toLowerCase())).size!==names.length){setupStatus('Selecciona un grupo y escribe nombres válidos y distintos para todos los integrantes.',true);return;}$('startButton').disabled=true;setupStatus('Registrando equipo y asignando un pack…');try{const data=await rpc(cfg.rpc.start,{p_student_names:names,p_group_code:group,p_session_id:crypto.randomUUID(),p_user_agent:navigator.userAgent});state.attemptId=data.attempt_id;state.token=data.attempt_token;save();setupStatus('');render(data.snapshot);await logEvent('OOP_LAB_READY',{team_size:names.length,variant_pack:data.snapshot?.variant_pack,workspace_version:'oop-logic-01-v1'});}catch(err){$('startButton').disabled=false;setupStatus(`No fue posible iniciar: ${err.message}`,true)}});

  async function logEvent(type,metadata={}){if(!state.attemptId||!state.token)return;try{await rpc(cfg.rpc.event,{p_attempt_id:state.attemptId,p_attempt_token:state.token,p_event_type:type,p_metadata:metadata})}catch{}}
  $('validateButton').addEventListener('click',async()=>{if(!state.selected||!state.current)return;$('validateButton').disabled=true;setStatus('Validando la lógica de la respuesta…');try{const data=await rpc(cfg.rpc.submit,{p_attempt_id:state.attemptId,p_attempt_token:state.token,p_checkpoint_key:state.current.key,p_answer:state.selected});if(data.correct){setStatus(`Correcto · ${Number(data.awarded_points||0).toFixed(2)} punto(s).`,'ok');await logEvent('OOP_QUESTION_CORRECT',{checkpoint_key:state.current.key,variant_key:state.current.variant_key});setTimeout(()=>render(data.snapshot),650)}else{updateMetrics(data.snapshot);state.current=(data.snapshot.checkpoints||[]).find(x=>x.key===state.current.key)||state.current;setStatus(`Respuesta incorrecta registrada. Intento #${Number(data.wrong_attempts||1)}. Revisa el modelo de objetos y vuelve a intentar.`,'bad');$('validateButton').disabled=false;}}catch(err){setStatus(`No se pudo validar: ${err.message}`,'bad');$('validateButton').disabled=false;}});

  $('helpButton').addEventListener('click',async()=>{if(!state.current)return;const remaining=Number(state.snapshot?.help_tokens_remaining||0);if(remaining<=0)return;if(!confirm(`¿Usar una ayuda? Quedan ${remaining}.`))return;try{const data=await rpc(cfg.rpc.help,{p_attempt_id:state.attemptId,p_attempt_token:state.token,p_checkpoint_key:state.current.key});updateMetrics(data.snapshot);state.current=(data.snapshot.checkpoints||[]).find(x=>x.key===state.current.key)||state.current;const guide=GUIDES[state.current.topic]||GUIDES.integrated_trace,level=Math.max(1,Math.min(3,Number(data.help_level||state.current.help_count||1))),text=level===1?guide.hints[0]:level===2?(data.variant_hint||guide.hints[1]):guide.hints[2];$('helpPanel').innerHTML=`<strong>Ayuda ${level}</strong><br>${esc(text)}`;$('helpPanel').classList.remove('hidden');setStatus('Ayuda registrada. Vuelve a justificar la respuesta antes de validar.');}catch(err){setStatus(`Ayuda no disponible: ${err.message}`,'bad')}});

  $('revealButton').addEventListener('click',async()=>{if(!state.current||!confirm('¿Revelar la respuesta correcta? La pregunta se cerrará con 25% del crédito.'))return;try{const data=await rpc(cfg.rpc.reveal,{p_attempt_id:state.attemptId,p_attempt_token:state.token,p_checkpoint_key:state.current.key});state.pendingSnapshot=data.snapshot;$('solutionAnswer').textContent=data.expected_answer||'—';$('solutionExplanation').textContent=data.explanation||'Revisa la relación entre los objetos y el estado descrito.';$('solutionOverlay').classList.remove('hidden');updateMetrics(data.snapshot);$('validateButton').disabled=true;$('revealButton').disabled=true;$('skipButton').disabled=true;}catch(err){setStatus(`No se pudo revelar: ${err.message}`,'bad')}});
  $('continueAfterReveal').addEventListener('click',()=>{$('solutionOverlay').classList.add('hidden');if(state.pendingSnapshot){const s=state.pendingSnapshot;state.pendingSnapshot=null;render(s)}});
  $('skipButton').addEventListener('click',async()=>{if(!state.current||!confirm('¿Omitir esta pregunta? Recibirá 0% de crédito.'))return;try{const data=await rpc(cfg.rpc.skip,{p_attempt_id:state.attemptId,p_attempt_token:state.token,p_checkpoint_key:state.current.key});render(data.snapshot)}catch(err){setStatus(`No se pudo omitir: ${err.message}`,'bad')}});

  window.addEventListener('beforeunload',e=>{if(state.snapshot&&!state.snapshot.completed){e.preventDefault();e.returnValue=''}});document.addEventListener('visibilitychange',()=>{if(state.attemptId&&document.hidden)logEvent('OOP_VISIBILITY_HIDDEN',{question_key:state.current?.key})});

  (async function restore(){const raw=sessionStorage.getItem(cfg.sessionKey);if(!raw)return;try{const saved=JSON.parse(raw);state.attemptId=saved.attemptId;state.token=saved.token;const data=await rpc(cfg.rpc.resume,{p_attempt_id:state.attemptId,p_attempt_token:state.token});render(data.snapshot)}catch{clearSaved();setupStatus('La sesión anterior ya no está disponible. Registra el equipo nuevamente.',true)}})();
})();
