(() => {
  'use strict';
  const cfg=window.IJR_OOP_LOGIC_CONFIG,$=id=>document.getElementById(id);
  const sb=window.supabase.createClient(cfg.supabaseUrl,cfg.supabasePublishableKey,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});
  let token=sessionStorage.getItem(cfg.teacherSessionKey)||'',snapshot=null,timer=null,loading=false;
  const VISIBLE_MS=3000,HIDDEN_MS=12000;
  async function rpc(name,args={}){const {data,error}=await sb.rpc(name,args);if(error)throw new Error(error.message||'Backend error');return data}
  function esc(v=''){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
  function fmt(v){return v==null?'—':Number(v).toFixed(2)}
  function fmtTime(v){if(!v)return'—';try{return new Date(v).toLocaleString('es-CO',{dateStyle:'short',timeStyle:'medium'})}catch{return'—'}}
  function schedule(ms){clearTimeout(timer);if(token)timer=setTimeout(load,ms)}
  function names(s){return Array.isArray(s?.participants)?s.participants:[]}
  function filtered(){if(!snapshot)return[];const g=$('groupFilter').value,q=$('searchInput').value.trim().toLowerCase(),active=$('activeOnly').checked;return Array.from(snapshot.sessions||[]).filter(s=>(!g||s.group_code===g)&&(!active||s.status==='active')&&(!q||names(s).some(p=>String(p.display_name||'').toLowerCase().includes(q))))}
  function render(){if(!snapshot)return;const rows=filtered(),active=rows.filter(s=>s.status==='active').length,students=rows.reduce((n,s)=>n+Number(s.team_size||names(s).length||1),0),grades=rows.map(s=>Number(s.status==='submitted'?s.grade:s.projected_grade)).filter(Number.isFinite),avg=grades.length?grades.reduce((a,b)=>a+b,0)/grades.length:null;$('metrics').innerHTML=[['Sesiones',rows.length],['Activas',active],['Estudiantes',students],['Promedio / proyección',avg==null?'—':avg.toFixed(2)],['Preguntas',12]].map(([k,v])=>`<div class="metric"><span>${esc(k)}</span><strong>${esc(v)}</strong></div>`).join('');$('rowCount').textContent=`${rows.length} mostradas`;$('sessionBody').innerHTML=rows.map(s=>{const participantHtml=names(s).map(p=>`<span>${esc(p.display_name)}</span>`).join(''),support=`H ${Number(s.helps||0)} · E ${Number(s.wrong_attempts||0)} · R ${Number(s.revealed_count||0)} · S ${Number(s.skipped_count||0)}`,mark=s.latest_answer_correct===true?'✓':s.latest_answer_correct===false?'✗':'·',aCls=s.latest_answer_correct===true?'answer-ok':s.latest_answer_correct===false?'answer-bad':'';return `<tr><td><strong>${esc(s.group_code||'—')}</strong></td><td><div class="students">${participantHtml||'<span>—</span>'}</div></td><td class="pack">${String(s.variant_pack??'—').padStart(2,'0')}</td><td><span class="badge ${s.status==='submitted'?'submitted':''}">${s.status==='submitted'?'Finalizada':'Activa'}</span></td><td><strong>${Number(s.completed_count||0)}/12</strong></td><td class="grade">${fmt(s.status==='submitted'?s.grade:s.projected_grade)}</td><td class="${aCls}"><strong>${esc(s.latest_checkpoint_key||'—')}</strong><div class="sub">${esc(s.latest_answer??'—')} ${mark}</div></td><td>${esc(support)}</td><td>${fmtTime(s.last_activity_at)}</td><td><button class="inspect" data-id="${esc(s.attempt_id)}">Inspeccionar</button></td></tr>`}).join('')||'<tr><td colspan="10" class="empty">No hay sesiones para este filtro.</td></tr>';$('updatedAt').textContent=`Actualizado ${new Date(snapshot.generated_at||Date.now()).toLocaleTimeString('es-CO')}`;document.querySelectorAll('.inspect[data-id]').forEach(b=>b.addEventListener('click',()=>openDetail(b.dataset.id)));}
  async function load(force=false){if(!token||loading)return;loading=true;try{snapshot=await rpc(cfg.rpc.teacherDashboard,{p_teacher_token:token});$('loginPanel').classList.add('hidden');$('dashboardPanel').classList.remove('hidden');$('liveStatus').textContent='LIVE';render();schedule(document.hidden?HIDDEN_MS:VISIBLE_MS)}catch(err){if(/invalid|expired|teacher session/i.test(err.message)){token='';sessionStorage.removeItem(cfg.teacherSessionKey);$('dashboardPanel').classList.add('hidden');$('loginPanel').classList.remove('hidden');$('loginStatus').textContent=`Sesión docente no disponible: ${err.message}`}else{$('liveStatus').textContent='STALE';schedule(force?VISIBLE_MS:Math.min(30000,VISIBLE_MS*2))}}finally{loading=false}}
  async function openDetail(id){$('dialogStatus').textContent='Cargando…';$('detailDialog').showModal();try{const data=await rpc(cfg.rpc.teacherDetail,{p_teacher_token:token,p_attempt_id:id}),a=data.attempt||{},ps=data.participants||[],rs=data.responses||[],events=data.events||[];$('dialogTitle').textContent=`${a.group_code||'—'} · ${ps.map(p=>p.display_name).join(' · ')}`;$('detailSummary').innerHTML=[['Estado',a.status],['Nota',fmt(a.grade)],['Pack',a.variant_pack],['Inicio',fmtTime(a.started_at)],['Última actividad',fmtTime(a.last_activity_at)]].map(([k,v])=>`<div><span>${esc(k)}</span><strong>${esc(v??'—')}</strong></div>`).join('');$('detailResponses').innerHTML=rs.map(r=>`<article class="response ${r.correct?'ok':r.completion_mode==='revealed'?'revealed':''}"><div class="response-head"><h4>${esc(r.sequence)} · ${esc(r.title)}</h4><strong>${esc(r.completion_mode||'pending')}</strong></div><p>${esc(r.prompt||'')}</p><div class="pair"><span>Respuesta</span><code>${esc(r.latest_answer??'—')}</code><span>Esperada</span><code>${esc(r.expected_answer??'—')}</code><span>Explicación</span><code>${esc(r.explanation??'—')}</code></div><small>intentos ${Number(r.try_count||0)} · errores ${Number(r.wrong_attempts||0)} · ayudas ${Number(r.help_count||0)} · puntos ${Number(r.awarded_points||0).toFixed(2)}</small></article>`).join('');$('detailEvents').innerHTML=events.map(e=>`<div class="event"><strong>${esc(e.event_type)}</strong><span>${fmtTime(e.created_at)}</span><code>${esc(JSON.stringify(e.metadata||{}))}</code></div>`).join('')||'Sin eventos.';$('dialogStatus').textContent=''}catch(err){$('dialogStatus').textContent=`No fue posible cargar el detalle: ${err.message}`}}
  $('loginForm').addEventListener('submit',async e=>{e.preventDefault();$('loginStatus').textContent='Ingresando…';try{const data=await rpc(cfg.rpc.teacherLogin,{p_code:$('teacherCode').value,p_user_agent:navigator.userAgent});token=data.teacher_token;sessionStorage.setItem(cfg.teacherSessionKey,token);$('teacherCode').value='';$('loginStatus').textContent='';await load(true)}catch(err){$('loginStatus').textContent=`No fue posible ingresar: ${err.message}`}});
  $('logoutButton').addEventListener('click',async()=>{try{if(token)await rpc(cfg.rpc.teacherLogout,{p_teacher_token:token})}catch{}token='';snapshot=null;clearTimeout(timer);sessionStorage.removeItem(cfg.teacherSessionKey);$('dashboardPanel').classList.add('hidden');$('loginPanel').classList.remove('hidden')});
  $('refreshButton').addEventListener('click',()=>load(true));$('groupFilter').addEventListener('change',render);$('activeOnly').addEventListener('change',render);$('searchInput').addEventListener('input',render);$('closeDialog').addEventListener('click',()=>$('detailDialog').close());document.addEventListener('visibilitychange',()=>{if(token){document.hidden?schedule(HIDDEN_MS):load(true)}});window.addEventListener('online',()=>{if(token)load(true)});if(token)load(true);
})();
