-- Seminar 11 Software Engineering Studio v1
-- Applied to production on 2026-08-24.

create table if not exists public.seminar_studio_profiles (
  id uuid primary key default gen_random_uuid(),
  response_id uuid not null unique default gen_random_uuid(),
  edit_token_hash text not null unique,
  created_at timestamptz not null default clock_timestamp(),
  updated_at timestamptz not null default clock_timestamp(),
  last_student_activity_at timestamptz not null default clock_timestamp(),
  teacher_updated_at timestamptz,
  full_name text not null check (char_length(trim(full_name)) between 3 and 140),
  group_code text not null check (group_code in ('11-A','11-B','11-C')),
  topics text[] not null,
  first_choice text not null,
  track_slug text not null check (track_slug in ('web','data-science','cybersecurity','3d-programming','robotics')),
  work_mode text not null check (work_mode in ('Individual','Pareja')),
  partner_name text,
  project_idea text,
  project_title text,
  repo_full_name text,
  uml_url text,
  sprint_current smallint not null default 1 check (sprint_current between 1 and 8),
  progress_percent smallint not null default 0 check (progress_percent between 0 and 100),
  next_goal text,
  status text not null default 'active' check (status in ('active','complete','paused')),
  teacher_note text,
  constraint seminar_studio_topics_count check (cardinality(topics) between 1 and 5),
  constraint seminar_studio_first_choice check (first_choice = any(topics)),
  constraint seminar_studio_partner check ((work_mode='Individual' and partner_name is null) or (work_mode='Pareja' and char_length(trim(coalesce(partner_name,''))) between 3 and 140)),
  constraint seminar_studio_repo_format check (repo_full_name is null or repo_full_name ~ '^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$')
);
comment on table public.seminar_studio_profiles is 'Private student route/profile state for Seminar 11 Software Engineering Studio. Browser clients have no direct table access; student writes/reads go through the constrained Edge Function and teacher reads/updates through the MFA gateway.';
create index if not exists seminar_studio_profiles_group_idx on public.seminar_studio_profiles(group_code,full_name);
create index if not exists seminar_studio_profiles_track_idx on public.seminar_studio_profiles(track_slug,sprint_current);
create index if not exists seminar_studio_profiles_activity_idx on public.seminar_studio_profiles(last_student_activity_at desc);
alter table public.seminar_studio_profiles enable row level security;
revoke all on table public.seminar_studio_profiles from public,anon,authenticated;
grant select,insert,update on table public.seminar_studio_profiles to service_role;

create table if not exists public.seminar_studio_events (
  id bigint generated by default as identity primary key,
  occurred_at timestamptz not null default clock_timestamp(),
  profile_id uuid references public.seminar_studio_profiles(id) on delete cascade,
  event_type text not null check (event_type in ('register','load','student_update','teacher_update')),
  payload jsonb not null default '{}'::jsonb,
  ip_hash text,
  user_agent text
);
comment on table public.seminar_studio_events is 'Private audit trail for Seminar 11 Studio profile lifecycle. No direct browser access.';
create index if not exists seminar_studio_events_profile_idx on public.seminar_studio_events(profile_id,occurred_at desc);
alter table public.seminar_studio_events enable row level security;
revoke all on table public.seminar_studio_events from public,anon,authenticated;
grant select,insert on table public.seminar_studio_events to service_role;

drop policy if exists seminar11_simple_public_insert on public.seminar11_simple_survey;
drop policy if exists survey_public_insert_only on public.seminar_project_survey_responses;
revoke insert,update,delete,select on table public.seminar11_simple_survey from anon,authenticated;
revoke insert,update,delete,select on table public.seminar_project_survey_responses from anon,authenticated;
comment on table public.seminar11_simple_survey is 'DEPRECATED 2026-08-24. Replaced by seminar_studio_profiles through the constrained seminar-studio-student Edge Function.';
comment on table public.seminar_project_survey_responses is 'DEPRECATED 2026-08-24. Replaced by seminar_studio_profiles through the constrained seminar-studio-student Edge Function.';

create or replace function public.seminar_studio_teacher_dashboard()
returns jsonb language sql security definer set search_path=''
as $$
  select jsonb_build_object('generated_at',clock_timestamp(),'students',coalesce(jsonb_agg(jsonb_build_object(
    'id',p.id,'response_id',p.response_id,'created_at',p.created_at,'updated_at',p.updated_at,
    'last_student_activity_at',p.last_student_activity_at,'teacher_updated_at',p.teacher_updated_at,
    'full_name',p.full_name,'group_code',p.group_code,'topics',p.topics,'first_choice',p.first_choice,
    'track_slug',p.track_slug,'work_mode',p.work_mode,'partner_name',p.partner_name,'project_idea',p.project_idea,
    'project_title',p.project_title,'repo_full_name',p.repo_full_name,'uml_url',p.uml_url,
    'sprint_current',p.sprint_current,'progress_percent',p.progress_percent,'next_goal',p.next_goal,
    'status',p.status,'teacher_note',p.teacher_note) order by p.group_code,p.full_name),'[]'::jsonb))
  from public.seminar_studio_profiles p;
$$;
revoke execute on function public.seminar_studio_teacher_dashboard() from public,anon,authenticated;
grant execute on function public.seminar_studio_teacher_dashboard() to service_role;

create or replace function public.seminar_studio_teacher_update(
  p_profile_id uuid,p_sprint_current smallint default null,p_progress_percent smallint default null,
  p_next_goal text default null,p_repo_full_name text default null,p_uml_url text default null,
  p_project_title text default null,p_status text default null,p_teacher_note text default null
) returns jsonb language plpgsql security definer set search_path=''
as $$
declare v_row public.seminar_studio_profiles;
begin
  if p_sprint_current is not null and (p_sprint_current<1 or p_sprint_current>8) then raise exception 'invalid_sprint'; end if;
  if p_progress_percent is not null and (p_progress_percent<0 or p_progress_percent>100) then raise exception 'invalid_progress'; end if;
  if p_status is not null and p_status not in ('active','complete','paused') then raise exception 'invalid_status'; end if;
  if p_repo_full_name is not null and p_repo_full_name<>'' and p_repo_full_name !~ '^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$' then raise exception 'invalid_repo'; end if;
  update public.seminar_studio_profiles set
    sprint_current=coalesce(p_sprint_current,sprint_current),progress_percent=coalesce(p_progress_percent,progress_percent),
    next_goal=coalesce(nullif(trim(p_next_goal),''),next_goal),
    repo_full_name=case when p_repo_full_name is null then repo_full_name else nullif(trim(p_repo_full_name),'') end,
    uml_url=case when p_uml_url is null then uml_url else nullif(trim(p_uml_url),'') end,
    project_title=case when p_project_title is null then project_title else nullif(trim(p_project_title),'') end,
    status=coalesce(p_status,status),teacher_note=case when p_teacher_note is null then teacher_note else nullif(trim(p_teacher_note),'') end,
    teacher_updated_at=clock_timestamp(),updated_at=clock_timestamp()
  where id=p_profile_id returning * into v_row;
  if not found then raise exception 'profile_not_found'; end if;
  insert into public.seminar_studio_events(profile_id,event_type,payload) values(v_row.id,'teacher_update',jsonb_build_object('sprint_current',v_row.sprint_current,'progress_percent',v_row.progress_percent,'status',v_row.status));
  return jsonb_build_object('ok',true,'id',v_row.id,'updated_at',v_row.updated_at);
end;
$$;
revoke execute on function public.seminar_studio_teacher_update(uuid,smallint,smallint,text,text,text,text,text,text) from public,anon,authenticated;
grant execute on function public.seminar_studio_teacher_update(uuid,smallint,smallint,text,text,text,text,text,text) to service_role;
