-- Production migration applied 2026-09-23.
-- Individual Seminar 11 project proposals, keyed to the official roster by group + canonical display name.

create table if not exists public.seminar_student_projects (
  student_registry_id uuid primary key references public.student_registry(id) on delete cascade,
  group_code text not null check (group_code in ('11A','11B','11C')),
  student_name text not null check (char_length(btrim(student_name)) between 3 and 140),
  project_slug text not null unique check (project_slug ~ '^[a-z0-9][a-z0-9-]{2,80}$'),
  track_slug text not null check (track_slug in ('web','data-science','cybersecurity','3d-programming','robotics')),
  project_title text not null check (char_length(btrim(project_title)) between 3 and 180),
  project_summary text not null,
  objective text not null,
  stack text[] not null default '{}',
  source_kind text not null default 'teacher',
  source_ref text,
  safety_scope text,
  sprints jsonb not null default '[]'::jsonb,
  assignment_status text not null default 'assigned' check (assignment_status in ('assigned','active','paused','complete')),
  teacher_note text,
  created_at timestamptz not null default clock_timestamp(),
  updated_at timestamptz not null default clock_timestamp(),
  constraint seminar_student_projects_sprints_array check (
    jsonb_typeof(sprints)='array' and jsonb_array_length(sprints)=8
  )
);

comment on table public.seminar_student_projects is
'Private teacher-defined individualized project plans for Seminar 11. Served only through constrained Edge Functions / MFA teacher gateway.';

create index if not exists seminar_student_projects_group_idx
  on public.seminar_student_projects(group_code,student_name);
create index if not exists seminar_student_projects_track_idx
  on public.seminar_student_projects(track_slug,assignment_status);

alter table public.seminar_student_projects enable row level security;
revoke all on table public.seminar_student_projects from public,anon,authenticated;
grant select,insert,update,delete on table public.seminar_student_projects to service_role;

with seed(group_code,student_name,project_slug,track_slug,project_title,project_summary,objective,stack,source_kind,source_ref,safety_scope,sprints,assignment_status,teacher_note) as (
values
('11A','ARANGO GIRALDO JUAN PABLO','arango-dos-defense-lab','cybersecurity','DoS Defense Lab — Local Traffic Simulator & Rate-Limit Dashboard','Laboratorio defensivo para observar cómo una aplicación web local responde a incrementos controlados de solicitudes y cómo las defensas reducen el impacto.','Construir una aplicación web de laboratorio, un generador de tráfico únicamente contra localhost y un panel que evidencie tasa de solicitudes, bloqueos, latencia y eventos de seguridad.',array['Python','FastAPI/Flask','JavaScript','logging','rate limiting']::text[],'teacher','2026-09-23 + user assignment','Únicamente localhost o un entorno de laboratorio expresamente autorizado. No se prueban objetivos externos, no se evade protección y no se genera tráfico contra servicios de terceros.','[{"n":1,"goal":"Define the local web service, authorized scope, threat scenario and measurable success criteria.","title":"Scope + protected asset","deliverable":"README scope + asset/threat table"},{"n":2,"goal":"Model Client, RequestGenerator, RateLimiter, AuditLog and Dashboard responsibilities.","title":"Architecture + UML V1","deliverable":"UML V1 + request-flow diagram"},{"n":3,"goal":"Build a small local endpoint and record normal request rate, latency and status codes.","title":"Baseline web service","deliverable":"Local app + baseline evidence"},{"n":4,"goal":"Generate bounded traffic only against localhost with configurable rate and duration.","title":"Controlled traffic simulator","deliverable":"Safe simulator + run configuration"},{"n":5,"goal":"Add rate limiting, cooldown/backoff rules and security logging.","title":"Defensive controls","deliverable":"Defense layer + blocked-request evidence"},{"n":6,"goal":"Visualize requests/sec, latency, allowed/blocked counts and event timeline.","title":"Monitoring dashboard","deliverable":"Dashboard + screenshots"},{"n":7,"goal":"Test normal, burst and invalid-input scenarios; document limits and refactor duplicated checks.","title":"Defensive QA","deliverable":"Test matrix + fixes + UML V2"},{"n":8,"goal":"Demonstrate the lab live and explain risks, mitigations and residual limitations.","title":"Security review + defense","deliverable":"Final demo + security report + UML"}]'::jsonb,'assigned',null),
('11A','GOMEZ CANO SAMUEL','gomez-gta-v-mod-hub','web','GTA V Mod Hub — Catalog, Compatibility & Install Guide','Aplicación web para organizar mods de GTA V por categoría, versión, requisitos, compatibilidad y estado de instalación.','Construir un catálogo web funcional con búsqueda, filtros, favoritos y una guía de instalación basada en datos estructurados, sin incluir bypass de anti-cheat ni evasión de controles.',array['HTML','CSS','JavaScript','JSON','localStorage']::text[],'github_issue','Issue #15 + teacher specification','El proyecto es un catálogo/gestor informativo. No incluye bypass de anti-cheat, evasión de DRM, ejecución de cheats, modificación maliciosa ni acceso no autorizado.','[{"n":1,"goal":"Define users, MVP and the fields needed for each mod: category, version, requirements, compatibility and source.","title":"Product scope + mod schema","deliverable":"README + JSON schema"},{"n":2,"goal":"Model Mod, Category, CompatibilityRule and FavoritesStore.","title":"Domain model + UML V1","deliverable":"UML V1 + sample objects"},{"n":3,"goal":"Build responsive cards and a detail view from JSON data.","title":"Catalog interface","deliverable":"Navigable catalog UI"},{"n":4,"goal":"Implement text search and filters by category, version and compatibility.","title":"Search + filters","deliverable":"Working search/filter flow"},{"n":5,"goal":"Explain whether a selected mod matches a chosen game version and required dependencies.","title":"Compatibility validator","deliverable":"Compatibility rules + visible explanations"},{"n":6,"goal":"Persist favorites and user preferences with localStorage.","title":"Favorites + persistence","deliverable":"Saved state + reset option"},{"n":7,"goal":"Test empty data, unknown versions, keyboard navigation and responsive layout; refactor.","title":"QA + accessibility","deliverable":"Test checklist + UML V2"},{"n":8,"goal":"Publish the site and defend data model, validation and design decisions.","title":"Release + defense","deliverable":"GitHub Pages URL + final UML + live demo"}]'::jsonb,'assigned',null),
('11A','MAZO LOPEZ JERONIMO','mazo-ai-image-classifier','data-science','AI Intro Lab — Image Classifier & Model Evaluation','Proyecto introductorio de inteligencia artificial centrado en clasificación de imágenes y evaluación transparente del rendimiento.','Entrenar y evaluar un clasificador sencillo con un conjunto de datos pequeño, explicando preparación de datos, predicción, errores y limitaciones.',array['Python','Jupyter/Colab','scikit-learn or Teachable Machine export','Pandas','Matplotlib']::text[],'github_issue','Issue #13 — Inteligencia Artificial Introductoria','Usar datasets públicos o propios sin datos sensibles; documentar limitaciones y evitar presentar el modelo como infalible.','[{"n":1,"goal":"Choose a small image-classification problem, define classes and success metric.","title":"Question + classes","deliverable":"Problem statement + class definitions"},{"n":2,"goal":"Model Dataset, Preprocessor, Classifier and Evaluator responsibilities.","title":"Pipeline + UML V1","deliverable":"UML V1 + pipeline sketch"},{"n":3,"goal":"Load, label, inspect and split the dataset while documenting class balance.","title":"Dataset preparation","deliverable":"Reproducible data-prep notebook"},{"n":4,"goal":"Train a first simple model and produce predictions.","title":"Baseline classifier","deliverable":"Baseline model + first metrics"},{"n":5,"goal":"Calculate accuracy and a confusion matrix; compare at least two settings or models.","title":"Evaluation","deliverable":"Metrics table + plots"},{"n":6,"goal":"Inspect misclassified examples and explain likely causes and limitations.","title":"Error analysis","deliverable":"Error-analysis section"},{"n":7,"goal":"Create a small prediction demo or clean notebook workflow and synchronize UML.","title":"Interface + refactor","deliverable":"Demo UI/notebook + UML V2"},{"n":8,"goal":"Run a new example live and defend dataset, model, metrics and limitations.","title":"AI defense","deliverable":"Final demo + report + final UML"}]'::jsonb,'assigned',null),
('11A','RODRIGUEZ PEÑA JERONIMO','rodriguez-robot-control-simulator','robotics','Robot Control Simulator — Sensors, State Machine & Fail-Safe','Simulador de un robot móvil o sistema automatizado que recibe sensores, toma decisiones por estados y controla actuadores con comportamiento seguro.','Implementar una arquitectura orientada a objetos de Sensor–Controller–Actuator, probar secuencias de entradas y agregar un estado fail-safe.',array['Python/MicroPython or Arduino','state machines','sensors','actuators','simulation']::text[],'teacher','2026-09-23 + user assignment','Primero simulación. Hardware real solo si está disponible y bajo condiciones seguras de alimentación, movimiento y montaje.','[{"n":1,"goal":"Define robot purpose, sensor inputs, actuator outputs and safety state.","title":"System requirement + I/O","deliverable":"I/O table + scenario list"},{"n":2,"goal":"Model Sensor, Controller, Actuator and Robot; define state transitions.","title":"UML + state diagram","deliverable":"UML V1 + state diagram"},{"n":3,"goal":"Generate deterministic sensor readings and show expected outputs before using hardware.","title":"Sensor simulation","deliverable":"Runnable sensor simulator"},{"n":4,"goal":"Implement controller classes and decision logic without UI/hardware coupling.","title":"OOP controller","deliverable":"Class-based control layer"},{"n":5,"goal":"Handle normal transitions, invalid readings, timeout and safe fallback.","title":"State machine + fail-safe","deliverable":"Fail-safe evidence + state tests"},{"n":6,"goal":"Test multiple sensor sequences against expected actuator responses.","title":"Scenario testing","deliverable":"Test matrix + fixes"},{"n":7,"goal":"Connect optional hardware or strengthen simulation with realistic timings and noise.","title":"Integration","deliverable":"Integrated prototype + UML V2"},{"n":8,"goal":"Run one normal and one failure scenario live and explain architecture.","title":"Robot demo + defense","deliverable":"Final prototype + UML + live defense"}]'::jsonb,'assigned',null),
('11B','ARBELAEZ ESCOBAR PEDRO PABLO','arbelaez-secure-web-portal','cybersecurity','Secure Web Portal — Authentication, Roles & Audit Log','Portal web de laboratorio para aprender seguridad defensiva mediante validación, roles, sesiones simuladas, registros de auditoría y análisis de amenazas.','Construir un sistema controlado donde se pueda demostrar separación de privilegios, validación de entradas y trazabilidad de eventos de seguridad.',array['Web/Python','input validation','RBAC','audit logging','threat modeling']::text[],'github_issue','Issue #12 — Defensive Cybersecurity as primary interest','Solo sistema propio o sandbox autorizado. No se realizan ataques a servicios externos ni se proporcionan técnicas para eludir autenticación real.','[{"n":1,"goal":"Define protected assets, user roles, allowed actions and defensive threat scenarios.","title":"Assets + roles + threat scope","deliverable":"Asset list + role matrix + threat model"},{"n":2,"goal":"Model User, Role, Session, Validator and AuditLog with trust boundaries.","title":"Security UML V1","deliverable":"UML V1 + trust-boundary diagram"},{"n":3,"goal":"Implement allow-list validation and safe error messages for forms.","title":"Input validation","deliverable":"Valid/invalid input tests"},{"n":4,"goal":"Separate identity check from role-based permissions in service classes.","title":"Authentication + authorization simulation","deliverable":"Auth/RBAC service layer"},{"n":5,"goal":"Record login, denial and privileged-action events with useful metadata.","title":"Audit trail","deliverable":"Audit viewer + event examples"},{"n":6,"goal":"Test denied role actions, malformed input and expired/invalid simulated sessions.","title":"Authorized misuse tests","deliverable":"Security test matrix + fixes"},{"n":7,"goal":"Reduce duplicate checks, exposed state and ambiguous privileges.","title":"Hardening + refactor","deliverable":"Hardening commit + UML V2"},{"n":8,"goal":"Explain risks, mitigations, residual limitations and demonstrate role boundaries.","title":"Security review + defense","deliverable":"Security report + final UML + live demo"}]'::jsonb,'assigned',null),
('11B','CHAVARRIAGA AVENDAÑO SAMUEL','chavarriaga-parametric-3d-print','3d-programming','Parametric 3D Print — Modular Desk Organizer Generator','Proyecto de diseño para impresión 3D donde un objeto funcional cambia dimensiones y distribución a partir de parámetros definidos por el usuario.','Construir un modelo paramétrico reproducible, validar dimensiones y exportar una pieza imprimible en STL con evidencia de iteración.',array['OpenSCAD or FreeCAD/Python','parametric CAD','STL','slicer','3D printing']::text[],'teacher','2026-09-23 + student expressed interest in 3D printing','La impresión física es opcional según disponibilidad. Se deben respetar tolerancias, dimensiones seguras y límites del equipo.','[{"n":1,"goal":"Define what the organizer stores, physical constraints and adjustable parameters.","title":"Use case + dimensions","deliverable":"Dimension sheet + MVP sketch"},{"n":2,"goal":"Model Part, ParameterSet, Transform and Assembly; choose coordinate convention.","title":"Geometry model + UML V1","deliverable":"UML V1 + parameter table"},{"n":3,"goal":"Generate the first parametric base and compartments.","title":"Base geometry","deliverable":"First generated 3D model"},{"n":4,"goal":"Encapsulate walls, holes, fillets/chamfers or repeated modules as reusable operations.","title":"Reusable features","deliverable":"Reusable parametric components"},{"n":5,"goal":"Compose parts and enforce minimum wall thickness and valid dimensions.","title":"Assembly + constraints","deliverable":"Constraint validation + assembled model"},{"n":6,"goal":"Export STL and inspect orientation, size, supports and obvious mesh issues.","title":"STL + printability","deliverable":"STL + slicer evidence"},{"n":7,"goal":"Print when available or simulate slicing; record one measured problem and improvement.","title":"Prototype iteration","deliverable":"Iteration log + UML V2"},{"n":8,"goal":"Change a parameter live, regenerate the model and explain design decisions.","title":"Final artifact + defense","deliverable":"Final STL/model + parameter demo + UML"}]'::jsonb,'assigned',null),
('11B','JARAMILLO PALACIO PABLO','jaramillo-project-board-web','web','Project Board Web App — Tasks, Sprints & Evidence','Aplicación web para organizar un proyecto por tareas, sprints, evidencias y porcentaje de avance.','Construir un tablero web orientado a objetos con persistencia local, filtros y visualización clara del estado del proyecto.',array['HTML','CSS','JavaScript','DOM','localStorage']::text[],'github_issue','Issue #14 — Web Development',null,'[{"n":1,"goal":"Define the user, task workflow and minimum useful board.","title":"Users + MVP","deliverable":"README problem statement + backlog"},{"n":2,"goal":"Model Project, Sprint, Task and Evidence relationships.","title":"Entities + UML V1","deliverable":"UML V1 + object examples"},{"n":3,"goal":"Build columns/cards and navigation with semantic HTML/CSS.","title":"Responsive board UI","deliverable":"Navigable board shell"},{"n":4,"goal":"Create, edit, move and complete tasks through domain classes.","title":"OOP task operations","deliverable":"Working class-based task flow"},{"n":5,"goal":"Persist project state and validate empty/invalid fields.","title":"Persistence + validation","deliverable":"localStorage/JSON flow + invalid cases"},{"n":6,"goal":"Filter by sprint/status and calculate visible project progress.","title":"Filters + progress","deliverable":"Filters + progress metrics"},{"n":7,"goal":"Test reload, boundary states, accessibility and responsive behavior; refactor.","title":"QA + refactor","deliverable":"Test checklist + UML V2"},{"n":8,"goal":"Publish the board and defend object model and persistence choices.","title":"Deploy + defense","deliverable":"GitHub Pages URL + final UML + demo"}]'::jsonb,'assigned',null),
('11B','RICO PARAMO ALEJANDRO','rico-portable-python-visual-show','data-science','Portable Python Visual Show — USB Launcher & Procedural Animation','Experiencia visual procedural hecha en Python y preparada para ejecutarse de forma portátil desde una memoria USB mediante un lanzador explícito.','Crear una animación interactiva o generativa con arquitectura orientada a objetos, empaquetarla para ejecución offline y verificar rutas relativas y portabilidad.',array['Python','Pygame or Manim','procedural animation','PyInstaller','portable launcher']::text[],'teacher','2026-09-23 — teacher override of previous route','La ejecución desde USB debe iniciarse manualmente por el usuario mediante un launcher visible. No se implementa autorun oculto, persistencia, ejecución automática del sistema operativo ni técnicas similares a malware.','[{"n":1,"goal":"Define the visual experience, duration/interaction and portable MVP.","title":"Visual concept + storyboard","deliverable":"Storyboard + acceptance criteria"},{"n":2,"goal":"Model Scene, VisualElement, Effect, Timeline/Controller and Launcher responsibilities.","title":"Animation UML V1","deliverable":"UML V1 + scene graph"},{"n":3,"goal":"Render a fluid first scene with deterministic timing.","title":"First animation loop","deliverable":"Runnable scene + frame/sample evidence"},{"n":4,"goal":"Implement reusable motion/effect classes and parameter controls.","title":"Reusable effects","deliverable":"At least three reusable visual effects"},{"n":5,"goal":"Load local assets and settings using relative paths so the project is portable.","title":"Assets + configuration","deliverable":"Offline asset/config flow"},{"n":6,"goal":"Create a packaged build or controlled Python environment plus a visible start.bat/manual launcher.","title":"Portable build","deliverable":"Portable folder + launcher instructions"},{"n":7,"goal":"Test on a removable drive or clean folder with no network; fix path/dependency failures.","title":"USB/offline QA","deliverable":"Compatibility checklist + fixes + UML V2"},{"n":8,"goal":"Launch manually from portable media, change one visual parameter live and explain architecture.","title":"Live visual defense","deliverable":"Final portable demo + UML + README"}]'::jsonb,'assigned',null),
('11C','CORTES PAJON SAMUEL','cortes-gta-v-data-layer','web','GTA V Mod Hub — Data Layer, Search & Compatibility Validator','Componente web centrado en la capa de datos y validación de compatibilidad para un catálogo de mods de GTA V.','Construir un módulo independiente que cargue datos JSON, normalice metadatos, ejecute búsquedas/filtros y explique reglas de compatibilidad.',array['JavaScript','JSON','data modeling','search','validation']::text[],'github_issue','Issue #15 — Desarrollo web GTA V','No incluye bypass de anti-cheat, cheats, evasión de DRM ni acceso no autorizado. Puede integrarse con el proyecto de Samuel Gómez manteniendo responsabilidades individuales verificables.','[{"n":1,"goal":"Define a robust schema for mods, versions, dependencies, categories and compatibility notes.","title":"Mod metadata specification","deliverable":"Data dictionary + sample JSON"},{"n":2,"goal":"Model Mod, Repository, SearchIndex and CompatibilityRule.","title":"Data UML V1","deliverable":"UML V1 + object examples"},{"n":3,"goal":"Load records and normalize missing/variant fields safely.","title":"JSON loader + normalization","deliverable":"Data loader + normalized dataset"},{"n":4,"goal":"Implement case-insensitive text search and combined filters.","title":"Search engine","deliverable":"Search/filter module"},{"n":5,"goal":"Evaluate game version and dependency rules and return explainable outcomes.","title":"Compatibility rules","deliverable":"Validator + explanations"},{"n":6,"goal":"Test malformed JSON, missing dependencies, unknown versions and combined filters.","title":"Automated tests","deliverable":"Test suite/checklist + fixes"},{"n":7,"goal":"Connect to a UI or Samuel Gómez catalog while preserving a standalone API/module.","title":"Integration + refactor","deliverable":"Integration evidence + UML V2"},{"n":8,"goal":"Demonstrate dataset loading, search and validation on new records.","title":"Release + defense","deliverable":"Published module/app + final UML + live demo"}]'::jsonb,'assigned',null),
('11C','GONZALEZ GIRALDO TOMAS','gonzalez-ai-text-classifier','data-science','AI Intro Lab — Text Classifier & Metrics','Proyecto introductorio de IA para clasificar textos cortos en categorías y evaluar el modelo con métricas interpretables.','Construir un clasificador sencillo de texto, documentar limpieza/tokenización, entrenamiento, evaluación y análisis de errores.',array['Python','Colab','Pandas','scikit-learn','Matplotlib']::text[],'github_issue','Issue #13 — Inteligencia Artificial Introductoria','Usar texto público o creado para el curso, evitar datos personales y documentar sesgos y limitaciones del conjunto de datos.','[{"n":1,"goal":"Define a two- or three-class text problem and a clear evaluation metric.","title":"Problem + labels","deliverable":"Problem statement + label guide"},{"n":2,"goal":"Model TextDataset, Cleaner, Vectorizer, Classifier and Evaluator.","title":"Pipeline + UML V1","deliverable":"UML V1 + pipeline"},{"n":3,"goal":"Load data, inspect class balance and apply minimal reproducible text cleaning.","title":"Clean + inspect data","deliverable":"Data-prep notebook"},{"n":4,"goal":"Vectorize text and train a simple baseline classifier.","title":"Baseline model","deliverable":"Working model + predictions"},{"n":5,"goal":"Calculate accuracy, precision/recall and confusion matrix where appropriate.","title":"Metrics","deliverable":"Metrics table + plots"},{"n":6,"goal":"Inspect mistakes and identify vocabulary/data limitations.","title":"Error + bias analysis","deliverable":"Error-analysis notes"},{"n":7,"goal":"Create a small input-to-prediction demo and clean reusable classes.","title":"Mini demo + refactor","deliverable":"Demo + UML V2"},{"n":8,"goal":"Classify unseen text live and defend model, metrics and limitations.","title":"AI defense","deliverable":"Final notebook/app + report + UML"}]'::jsonb,'assigned',null),
('11C','RINCON TORRES ALEJANDRO','rincon-ai-recommender','data-science','AI Intro Lab — Recommendation Engine & Similarity Explorer','Proyecto introductorio de IA que recomienda elementos mediante similitud entre características y explica por qué aparecen en el ranking.','Construir un recomendador content-based sencillo, calcular similitud, producir un top-N y evaluar casos límite.',array['Python','Pandas','scikit-learn','cosine similarity','Matplotlib']::text[],'github_issue','Issue #13 — Inteligencia Artificial Introductoria','Usar datos no sensibles. Las recomendaciones deben presentarse como resultados del modelo y no como decisiones humanas definitivas.','[{"n":1,"goal":"Choose items and define what makes two items similar and what a useful recommendation means.","title":"Recommendation problem","deliverable":"Problem statement + feature list"},{"n":2,"goal":"Model ItemCatalog, FeatureBuilder, SimilarityEngine and Recommender.","title":"Model + UML V1","deliverable":"UML V1 + pipeline"},{"n":3,"goal":"Load/clean item data and build a documented feature representation.","title":"Dataset + features","deliverable":"Prepared dataset + feature table"},{"n":4,"goal":"Calculate cosine similarity or another justified simple metric.","title":"Similarity engine","deliverable":"Similarity matrix/sample"},{"n":5,"goal":"Rank and return recommendations with concise explanations.","title":"Top-N recommendations","deliverable":"Recommender function + examples"},{"n":6,"goal":"Test duplicates, sparse items, unknown items and different feature weightings.","title":"Quality + edge cases","deliverable":"Test cases + comparison"},{"n":7,"goal":"Create a simple notebook/app explorer and synchronize reusable classes with UML.","title":"Explorer UI + refactor","deliverable":"Explorer + UML V2"},{"n":8,"goal":"Generate a live recommendation for a new selection and explain similarity and limitations.","title":"Recommendation defense","deliverable":"Final demo + findings + UML"}]'::jsonb,'assigned',null),
('11C','VELASQUEZ BELTRAN SAMUEL','velasquez-school-events-web','web','School Events Web App — Events, Registration & Calendar','Aplicación web para publicar eventos escolares, filtrar actividades y simular registros con persistencia local.','Construir una aplicación web orientada a objetos con calendario/listado de eventos, validación de cupos y almacenamiento local.',array['HTML','CSS','JavaScript','DOM','localStorage']::text[],'github_issue','Issue #14 — Desarrollo web',null,'[{"n":1,"goal":"Define event organizer/user needs, core fields and minimum registration flow.","title":"Requirements + MVP","deliverable":"README + backlog"},{"n":2,"goal":"Model Event, Registration, Participant and EventStore.","title":"Entities + UML V1","deliverable":"UML V1 + sample objects"},{"n":3,"goal":"Build responsive list/cards and event detail view.","title":"Events interface","deliverable":"Navigable UI shell"},{"n":4,"goal":"Create and manipulate events through domain classes and DOM events.","title":"OOP event operations","deliverable":"Working event feature"},{"n":5,"goal":"Filter by date/category and provide a clear chronological/calendar representation.","title":"Filters + calendar view","deliverable":"Filters + calendar/list view"},{"n":6,"goal":"Validate capacity and participant fields and persist state locally.","title":"Registration + persistence","deliverable":"Registration flow + localStorage"},{"n":7,"goal":"Test full capacity, invalid dates, reload, keyboard use and responsive layout; refactor.","title":"QA + accessibility","deliverable":"Test checklist + UML V2"},{"n":8,"goal":"Publish and demonstrate creation/browsing/registration plus architecture.","title":"Release + defense","deliverable":"GitHub Pages URL + final UML + live defense"}]'::jsonb,'assigned',null)
)
insert into public.seminar_student_projects(
  student_registry_id,group_code,student_name,project_slug,track_slug,project_title,project_summary,objective,stack,
  source_kind,source_ref,safety_scope,sprints,assignment_status,teacher_note
)
select r.id,s.group_code,s.student_name,s.project_slug,s.track_slug,s.project_title,s.project_summary,s.objective,s.stack,
       s.source_kind,s.source_ref,s.safety_scope,s.sprints,s.assignment_status,s.teacher_note
from seed s
join public.student_registry r
  on r.active=true
 and r.group_code=s.group_code
 and upper(r.display_name)=upper(s.student_name)
on conflict (student_registry_id) do update set
  project_slug=excluded.project_slug,
  track_slug=excluded.track_slug,
  project_title=excluded.project_title,
  project_summary=excluded.project_summary,
  objective=excluded.objective,
  stack=excluded.stack,
  source_kind=excluded.source_kind,
  source_ref=excluded.source_ref,
  safety_scope=excluded.safety_scope,
  sprints=excluded.sprints,
  assignment_status=excluded.assignment_status,
  teacher_note=excluded.teacher_note,
  updated_at=clock_timestamp();
