alter table public.seminar_student_projects
  add column if not exists initial_project_title text,
  add column if not exists initial_project_summary text,
  add column if not exists initial_objective text,
  add column if not exists initial_stack text[],
  add column if not exists student_choice_key text
    check (student_choice_key is null or student_choice_key ~ '^[a-z0-9][a-z0-9-]{1,79}$'),
  add column if not exists student_decision_note text,
  add column if not exists student_decided_at timestamptz,
  add column if not exists student_revision_count integer not null default 0
    check (student_revision_count >= 0);

update public.seminar_student_projects
set initial_project_title = coalesce(initial_project_title, project_title),
    initial_project_summary = coalesce(initial_project_summary, project_summary),
    initial_objective = coalesce(initial_objective, objective),
    initial_stack = coalesce(initial_stack, stack);

comment on column public.seminar_student_projects.initial_project_title
  is 'Immutable-style snapshot of the teacher proposal title before student self-selection.';
comment on column public.seminar_student_projects.initial_project_summary
  is 'Snapshot of the teacher proposal summary before student self-selection.';
comment on column public.seminar_student_projects.initial_objective
  is 'Snapshot of the teacher proposal objective before student self-selection.';
comment on column public.seminar_student_projects.initial_stack
  is 'Snapshot of the teacher proposal tool stack before student self-selection.';
comment on column public.seminar_student_projects.student_choice_key
  is 'Option key selected by the student in the Seminar 11 Projects decision center.';
comment on column public.seminar_student_projects.student_decision_note
  is 'Optional note written by the student when confirming or revising the final project.';
comment on column public.seminar_student_projects.student_decided_at
  is 'Most recent timestamp when the student confirmed the project decision.';
comment on column public.seminar_student_projects.student_revision_count
  is 'Number of confirmed student project saves, including later revisions.';

create index if not exists seminar_student_projects_student_decision_idx
  on public.seminar_student_projects(decision_status, student_decided_at desc, group_code);

create table if not exists public.seminar_project_decision_events (
  id bigint generated by default as identity primary key,
  occurred_at timestamptz not null default clock_timestamp(),
  student_registry_id uuid not null
    references public.student_registry(id) on delete cascade,
  choice_key text not null,
  revision_number integer not null check (revision_number >= 1),
  previous_project jsonb not null,
  new_project jsonb not null,
  student_note text,
  ip_hash text,
  user_agent text
);

create index if not exists seminar_project_decision_events_student_idx
  on public.seminar_project_decision_events(student_registry_id, occurred_at desc);

alter table public.seminar_project_decision_events enable row level security;

revoke all on table public.seminar_project_decision_events from public, anon, authenticated;
grant select, insert on table public.seminar_project_decision_events to service_role;
grant usage, select on sequence public.seminar_project_decision_events_id_seq to service_role;

create or replace function public.seminar_student_project_save_decision(
  p_student_registry_id uuid,
  p_choice_key text,
  p_project_title text,
  p_project_summary text,
  p_objective text,
  p_stack text[],
  p_student_note text default null,
  p_ip_hash text default null,
  p_user_agent text default null
) returns jsonb
language plpgsql
security definer
set search_path=''
as $fn$
declare
  v_before public.seminar_student_projects;
  v_after public.seminar_student_projects;
  v_stack text[];
  v_now timestamptz := clock_timestamp();
begin
  if p_student_registry_id is null then
    raise exception 'student_registry_id_required';
  end if;

  if p_choice_key is null
     or p_choice_key !~ '^[a-z0-9][a-z0-9-]{1,79}$' then
    raise exception 'invalid_choice_key';
  end if;

  if p_project_title is null
     or char_length(btrim(p_project_title)) < 3
     or char_length(btrim(p_project_title)) > 180 then
    raise exception 'invalid_project_title';
  end if;

  if p_project_summary is null
     or char_length(btrim(p_project_summary)) < 10
     or char_length(btrim(p_project_summary)) > 1600 then
    raise exception 'invalid_project_summary';
  end if;

  if p_objective is null
     or char_length(btrim(p_objective)) < 10
     or char_length(btrim(p_objective)) > 1200 then
    raise exception 'invalid_objective';
  end if;

  if p_student_note is not null and char_length(btrim(p_student_note)) > 1200 then
    raise exception 'invalid_student_note';
  end if;

  select coalesce(array_agg(btrim(x)), '{}'::text[])
    into v_stack
  from unnest(coalesce(p_stack, '{}'::text[])) as x
  where btrim(x) <> '';

  if coalesce(array_length(v_stack, 1), 0) > 12
     or exists (
       select 1
       from unnest(v_stack) as x
       where char_length(x) > 80
     ) then
    raise exception 'invalid_stack';
  end if;

  select *
    into v_before
  from public.seminar_student_projects
  where student_registry_id = p_student_registry_id
  for update;

  if not found then
    raise exception 'student_project_not_found';
  end if;

  update public.seminar_student_projects
  set project_title = btrim(p_project_title),
      project_summary = btrim(p_project_summary),
      objective = btrim(p_objective),
      stack = v_stack,
      student_choice_key = p_choice_key,
      student_decision_note = nullif(btrim(p_student_note), ''),
      student_decided_at = v_now,
      student_revision_count = student_revision_count + 1,
      decision_status = 'confirmed',
      confirmed_at = v_now,
      assignment_status = case
        when assignment_status = 'assigned' then 'active'
        else assignment_status
      end,
      updated_at = v_now
  where student_registry_id = p_student_registry_id
  returning * into v_after;

  insert into public.seminar_project_decision_events(
    student_registry_id,
    choice_key,
    revision_number,
    previous_project,
    new_project,
    student_note,
    ip_hash,
    user_agent
  ) values (
    p_student_registry_id,
    p_choice_key,
    v_after.student_revision_count,
    to_jsonb(v_before),
    to_jsonb(v_after),
    nullif(btrim(p_student_note), ''),
    nullif(btrim(p_ip_hash), ''),
    nullif(left(p_user_agent, 1000), '')
  );

  return jsonb_build_object(
    'ok', true,
    'student_registry_id', v_after.student_registry_id,
    'project_title', v_after.project_title,
    'project_summary', v_after.project_summary,
    'objective', v_after.objective,
    'stack', v_after.stack,
    'student_choice_key', v_after.student_choice_key,
    'student_decision_note', v_after.student_decision_note,
    'student_decided_at', v_after.student_decided_at,
    'student_revision_count', v_after.student_revision_count,
    'decision_status', v_after.decision_status,
    'confirmed_at', v_after.confirmed_at,
    'updated_at', v_after.updated_at
  );
end;
$fn$;

revoke execute on function public.seminar_student_project_save_decision(
  uuid,text,text,text,text,text[],text,text,text
) from public, anon, authenticated;
grant execute on function public.seminar_student_project_save_decision(
  uuid,text,text,text,text,text[],text,text,text
) to service_role;

create or replace function public.seminar_studio_teacher_dashboard()
returns jsonb
language sql
security definer
set search_path=''
as $fn$
select jsonb_build_object(
  'generated_at', clock_timestamp(),
  'students', coalesce((
    select jsonb_agg(jsonb_build_object(
      'id',p.id,'response_id',p.response_id,'created_at',p.created_at,'updated_at',p.updated_at,
      'last_student_activity_at',p.last_student_activity_at,'teacher_updated_at',p.teacher_updated_at,
      'full_name',p.full_name,'group_code',p.group_code,'topics',p.topics,'first_choice',p.first_choice,
      'track_slug',p.track_slug,'work_mode',p.work_mode,'partner_name',p.partner_name,'project_idea',p.project_idea,
      'project_title',p.project_title,'repo_full_name',p.repo_full_name,'uml_url',p.uml_url,
      'sprint_current',p.sprint_current,'progress_percent',p.progress_percent,'next_goal',p.next_goal,
      'status',p.status,'teacher_note',p.teacher_note,'student_registry_id',p.student_registry_id
    ) order by p.group_code,p.full_name)
    from public.seminar_studio_profiles p
  ), '[]'::jsonb),
  'assignments', coalesce((
    select jsonb_agg(jsonb_build_object(
      'student_registry_id',a.student_registry_id,'group_code',a.group_code,'student_name',a.student_name,
      'project_slug',a.project_slug,'track_slug',a.track_slug,'project_title',a.project_title,
      'project_summary',a.project_summary,'objective',a.objective,'stack',a.stack,
      'initial_project_title',a.initial_project_title,'initial_project_summary',a.initial_project_summary,
      'initial_objective',a.initial_objective,'initial_stack',a.initial_stack,
      'source_kind',a.source_kind,'source_ref',a.source_ref,'safety_scope',a.safety_scope,
      'sprints',a.sprints,'assignment_status',a.assignment_status,'teacher_note',a.teacher_note,
      'decision_status',a.decision_status,'decision_note',a.decision_note,'confirmed_at',a.confirmed_at,
      'student_choice_key',a.student_choice_key,'student_decision_note',a.student_decision_note,
      'student_decided_at',a.student_decided_at,'student_revision_count',a.student_revision_count,
      'project_mode',a.project_mode,'definition_questions',a.definition_questions,'updated_at',a.updated_at
    ) order by a.group_code,a.student_name)
    from public.seminar_student_projects a
  ), '[]'::jsonb)
);
$fn$;

revoke execute on function public.seminar_studio_teacher_dashboard() from public, anon, authenticated;
grant execute on function public.seminar_studio_teacher_dashboard() to service_role;
